model: Goedel-LM/Goedel-Prover-V2-32B
api: vllm
temperature: 1.0
max_tokens: 40960
top_p: 0.95
max_model_len: 096
read_cost: 0
write_cost: 0
n_gpus: 4
node: 1
base_output_template: qwen
effective_parameters: 32
