model: openai/gpt-oss-120b
api: together
max_tokens: 40960
read_cost: 0.15
write_cost: 0.6
temperature: 1.0
reasoning_effort: low
system_prompt: 'You are ChatGPT, a large language model trained by OpenAI.

  '
tokenizer_kwargs:
  reasoning_effort: low
  model_identity: You are OpenAI GPT OSS.
base_output_template: api
effective_parameters: 5.1
